const config = [
    {
        'name':'glock',
        'index':'WEAPON_COMBATPISTOL',
        'type':'WEAPON_PISTOL_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'desert eagle',
        'index':'WEAPON_PISTOL50',
        'type':'WEAPON_PISTOL_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'mp5',
        'index':'WEAPON_SMG',
        'type':'WEAPON_SMG_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'m4a1',
        'index':'WEAPON_CARBINERIFLE',
        'type':'WEAPON_RIFLE_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'g36c',
        'index':'WEAPON_SPECIALCARBINE',
        'type':'WEAPON_RIFLE_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'remington',
        'index':'WEAPON_PUMPSHOTGUN',
        'type':'WEAPON_SHOTGUN_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'mossberg 590',
        'index':'WEAPON_SAWNOFFSHOTGUN',
        'type':'WEAPON_SHOTGUN_AMMO',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'teazer',
        'index':'WEAPON_STUNGUN',
        'type':'',
        'img':'164px-Assault-rifle-icon'
    },
    {
        'name':'extintor',
        'index':'WEAPON_FIREEXTINGUISHER',
        'type':'',
        'img':'164px-Assault-rifle-icon'
    },
]